### PR TITLE
Implements #182

### PR DESCRIPTION
**Pull request by bradmartin**

### CODE REVIEW

**Comment by bradmartin** [comment]
Implements #182 

This is an optional setting for the consumer to pass when calling `isEnabled(options)`.

I've mentioned this on the camera plugin, and plan to implement the same flow in a PR shortly as well. @tbozhikov liked the suggestion there.

I've ran into a situation where I'd like to open the settings is the enabled check resolves false and this.

**Comment by bradmartin** [comment]
Just realized currently android has options for `isEnabled` so going to change this accordingly and just add new value to the `Options` interface about iOS doing this when it fails.

**Comment by bradmartin** [comment]
Okay, made the change necessary. So now the `Options` can be passed to `isEnabled` on iOS as well, but the only check will be for the new prop value to open the settings if it is disabled.

**Comment by bradmartin** [comment]
Added doc on the typings about iOS using the new value for the `isEnabled` method.

**Comment by bradmartin** [comment]
Working more on this UX flow today in an app and even this would sometimes be the wrong approach.

Scenario:  `isEnabled` is false and we open the settings app without ever having presented the user with the location permission. At this point `Location` would not be listed in the settings since the user has not had a chance to `Allow` or `Deny` it.

Only when the status is `kCLAuthorizationStatusDenied` has the user denied it on their device. This would be the scenario where opening the settings on iOS would make sense. 

I'm going to rethink this PR a bit and see if I can provide a more elegant approach without breaking anything.

**Comment by bradmartin** [comment]
@lini @tbozhikov - not sure who is doing most of the work on this plugin anymore but know you're both contributors 😄.

This PR has changed a bit since I first created it so I want to recap the status and why so you're aware of the details.

I have an app where I've been getting logs with `locationManagerDidChangeAuthorizationStatus` in it, you can see this [Sentry log](https://sentry.io/share/issue/73edb28a996c49a6b963927862d3974e/) if you'd like.

So I went digging and my use case was fairly standard, check if the geolocation was enabled and  then try to get the current location.

Of course if the user has previously denied the Location permission prompt iOS provides, nothing happens. 

So this PR is providing two separate things:

1. The new `iosOpenSettingsIfLocationHasBeenDenied` on the `Options` interface which is already an argument on android. I didn't like using that but I didn't want to break anything, feel free to improve this by redoing some of the current logic if necessary. So when this is true for the `isEnabled` function, it will check if the Auth status has been denied (user had their chance to allow location permission the one time iOS does) and if so it will open the settings so they can change the location permission then quickly get back to the app and try again.

2. `getIOSLocationManagerStatus` new method iOS only that just returns the auth status of the CLLocationManager. I think this is all that is required but I did not test heavily since it requires uninstalling and reinstalling over and over to get the initial permission prompt on iOS.

I believe everything has been documented on the README and that this is not a breaking change since android remains the same and only iOS has been altered with a new configuration option on the `isEnabled` method.

**Comment by tbozhikov** [comment]
new PR with some tweaks added -> #185, good job @bradmartin!

**Pull request closed without merging**
