### PR TITLE
Update location permission reqs for iOS

### PR DESCRIPTION
**Pull request by rynop**
NSLocationAlwaysUsageDescription deprecated, use NSLocationAlwaysAndWhenInUseUsageDescription.

NSLocationUsageDescription is a macOS key.

### CODE REVIEW

**Comment by rynop** [comment]
@cla-bot check

**Comment by Prefix1802** [comment]
Can someone please fix this? Would be very much appreciated. :)

**Comment by rynop** [comment]
@VladimirAmiorkov done. thanks.

**Comment by elena-p** [comment]
run ci

**Pull request merged**
