### PR TITLE
Implement flexible version support for Google Play Services

### LINKED ISSUE #81: Incompatibility with nativescript-plugin-firebase
There's a version conflict between nativescript-geolocation and nativescript-plugin-firebase.

As of

https://github.com/NativeScript/nativescript-geolocation/blob/d47fc8dc45ceffa3c2a39b8c48d3099937a1e414/src/platforms/android/include.gradle#L19

nativescript-geolocation wants Google Play Services 11.4.0 but [nativescript-plugin-firebase forces me to pin to version 11.2.2](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#includegradle-failed-to-apply-plugin--for-input-string-).

Is version 11.4.0 actually really required for this plugin to work or can you just pin to 11.2.2 as well? I think this is a issue for many people because nativescript-plugin-firebase is quite an important plugin... If not, what could I do about it? I really would like to be able using both of these plugins together in one app.

Here's the original error message I get after installing the nativescript-geolocation plugin and trying to build for Android.

>FAILURE: Build failed with an exception.
>
>* What went wrong:
>Execution failed for task ':processF0F1F2F3F4F5F6F7DebugGoogleServices'.
>> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.4.0.

>>>

### PR DESCRIPTION
**Pull request by hettiger**
Closes #81

### CODE REVIEW

**Comment by DimitarTachev** [comment]
@hettiger, thank you for the contribution!

You could also add a similar README section as[ the one in the Firebase Plugin](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#includegradle-failed-to-apply-plugin--for-input-string-) in order to make this feature more visible.

We will try to upload the fix in NPM till the end of the week.

**Comment by hettiger** [comment]
@DimitarTachev I've added a readme update. Looking forward to install from NPM next week, thank you 👍

**Comment by hettiger** [comment]
Hello @ivanblazevic 

Before I have a closer look: Can you please try pinning to 11.2.2?
For your reference, here are my dependencies and app.gradle file contents:

```json
  "nativescript": {
    "id": "tld.example.id",
    "tns-android": {
      "version": "3.2.0"
    },
    "tns-ios": {
      "version": "3.2.0"
    }
  },
  "dependencies": {
    "@angular/animations": "^4.4.5",
    "@angular/common": "^4.4.5",
    "@angular/compiler": "^4.4.5",
    "@angular/core": "^4.4.5",
    "@angular/forms": "^4.4.5",
    "@angular/http": "^4.4.5",
    "@angular/platform-browser": "^4.4.5",
    "@angular/router": "^4.4.5",
    "lodash": "^4.17.4",
    "nativescript-angular": "^4.4.1",
    "nativescript-cardview": "^2.0.3",
    "nativescript-dom": "^2.0.0",
    "nativescript-geolocation": "file:plugins/nativescript-geolocation/nativescript-geolocation-4.1.1.tgz",
    "nativescript-google-maps-sdk": "^2.4.1",
    "nativescript-iqkeyboardmanager": "^1.1.0",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-orientation": "git+https://github.com/DimitarTachev/nativescript-orientation.git",
    "nativescript-plugin-firebase": "^4.1.2",
    "nativescript-ripple": "^2.0.0",
    "nativescript-telerik-ui": "^3.1.4",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-webview-interface": "1.4.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.2",
    "sanitizer": "^0.1.3",
    "tns-core-modules": "^3.2.0",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.4.5",
    "@ngtools/webpack": "~1.5.0",
    "babel-traverse": "6.25.0",
    "babel-types": "6.25.0",
    "babylon": "6.17.4",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "^3.0.1",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-sass": "^1.3.2",
    "nativescript-dev-typescript": "^0.5.1",
    "nativescript-dev-webpack": "^0.7.3",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "^2.1.1",
    "tns-platform-declarations": "^3.2.0",
    "typescript": "~2.4.2",
    "webpack": "~3.2.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1",
    "@types/lodash": "^4.14.77"
  },
```

```gradle
android {  
  defaultConfig {  
    generatedDensities = []
    applicationId = "tld.example.id"  
  }  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }
  project.ext {
    googlePlayServicesVersion = "11.2.2"
    supportVersion = "25.3.1"
  }
}

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.3.1'
            }
        }
    }
}
```

The app is working on both Android and iOS. Webpack builds are also working just fine.

**Comment by ivanblazevic** [comment]
@hettiger it looks like the problem was caused by `nativescript-push-notifications` plugin, after I updated include.gradle of the plugin to: `def firebaseMessagingVersion = project.hasProperty('firebaseMessagingVersion') ? project.firebaseMessagingVersion : '11.2.2'` build was ok. Well, this looks like a workaround but at least I'm able to build the project now. I have also tried your suggestion to pin specific version but the problem still persisted.

**Comment by hettiger** [comment]
@ivanblazevic try something like this in your app.gradle file:

```gradle
android {  
  defaultConfig {  
    generatedDensities = []
    applicationId = "tld.example.id"  
  }  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }
  project.ext {
    googlePlayServicesVersion = "11.2.2"
    firebaseMessagingVersion = "11.2.2"
    supportVersion = "25.3.1"
  }
}

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.3.1'
            }
        }
    }
}
```

**Comment by ivanblazevic** [comment]
@hettiger that did the trick, thx! Now I just need to figure out why I'm still getting `Timeout while searching for location!` error in simulator.

**Comment by hettiger** [comment]
@ivanblazevic that's good news, awesome! Can't tell you much about the timeout error. Are you using Genymotion, Android Studio or iOS Simulator? (You usually have to enable geolocation debugging and give it some coordinates to work with etc.)

**Comment by ivanblazevic** [comment]
@hettiger I'm using android emulator and also found what is the problem, it looks like I need to click on send button in extended controls > location to send coordinates manually each time after restart of the app.

**Pull request merged**
